# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actual',
            unique_together=set([('actual_rns', 'actual_arr', 'actual_rev')]),
        ),
    ]
