# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_desc',
            new_name='description',
        ),
    ]
