# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0002_auto_20170922_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEGMENTATION_LIST',
            fields=[
                ('SEG_ID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('SEG_TYPE', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GROUP_SEGMENT_MASTER',
            fields=[
                ('GRP_SEG_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rfs.SEGMENTATION_LIST')),
                ('GRP_SEG_NAME', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='INDIVIDUAL_SEGMENT_MASTER',
            fields=[
                ('IND_SEG_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rfs.SEGMENTATION_LIST')),
                ('IND_SEG_NAME', models.CharField(max_length=45)),
            ],
        ),
    ]
