# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0002_auto_20170922_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment_list',
            fields=[
                ('seg_id', models.AutoField(primary_key=True, serialize=False)),
                ('seg_type', models.CharField(max_length=6)),
            ],
        ),
    ]
