# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0002_auto_20171128_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actual',
            unique_together=set([]),
        ),
    ]
