# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0003_segment_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_segment',
            fields=[
                ('ind_seg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ind_seg_nme', models.IntegerField(max_length=25)),
            ],
        ),
    ]
