# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0004_individual_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_segment',
            name='ind_seg_nme',
            field=models.CharField(max_length=25),
        ),
    ]
