# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0004_auto_20170926_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='excel_file',
        ),
    ]
