# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0005_auto_20170926_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_segment',
            name='ind_seg_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rfs.Segment_list'),
        ),
    ]
