# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0006_auto_20170926_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_segment',
            name='ind_seg_id',
        ),
        migrations.AlterField(
            model_name='segment_list',
            name='seg_type',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Individual_segment',
        ),
    ]
