# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0007_auto_20170926_1420'),
        ('rfs', '0005_auto_20170926_1323'),
    ]

    operations = [
    ]
