# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0007_auto_20170926_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_segment',
            fields=[
                ('ind_seg_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rfs.Segment_list')),
                ('grp_seg_name', models.CharField(max_length=25)),
            ],
        ),
    ]
