# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0008_individual_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_segment',
            fields=[
                ('grp_seg_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rfs.Segment_list')),
                ('grp_seg_nme', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='individual_segment',
            old_name='grp_seg_name',
            new_name='ind_seg_nme',
        ),
    ]
