# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0008_merge_20170926_1544'),
        ('rfs', '0009_auto_20170926_1512'),
    ]

    operations = [
    ]
