# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0005_auto_20170926_1323'),
        ('rfs', '0009_auto_20170926_1512'),
    ]

    operations = [
    ]
