# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0010_merge_20170926_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('actual_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SEG_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='rfs.Segment_list')),
                ('DATE', models.DateField()),
                ('BUDGET_RNS', models.FloatField()),
                ('BUDGET_ARR', models.FloatField()),
                ('BUDGET_REVENUE', models.FloatField()),
                ('ACTUAL_RNS', models.FloatField()),
                ('ACTUAL_ARR', models.FloatField()),
                ('ACTUAL_REVENUE', models.FloatField()),
                ('PROJECT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfs.Project')),
            ],
        ),
        migrations.AlterModelOptions(
            name='group_segment',
            options={'ordering': ['grp_seg_id']},
        ),
        migrations.AlterModelOptions(
            name='individual_segment',
            options={'ordering': ['ind_seg_id']},
        ),
        migrations.AlterModelOptions(
            name='segment_list',
            options={'ordering': ['seg_id']},
        ),
        migrations.AlterField(
            model_name='file',
            name='excel_file',
            field=models.FileField(upload_to='projects/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
