# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0010_merge_20170926_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('actual_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('budget_rns', models.FloatField()),
                ('budget_arr', models.FloatField()),
                ('budget_rev', models.FloatField()),
                ('actual_rns', models.FloatField()),
                ('actual_arr', models.FloatField()),
                ('actual_rev', models.FloatField()),
            ],
            options={
                'ordering': ['actual_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='group_segment',
            options={'ordering': ['grp_seg_id']},
        ),
        migrations.AlterModelOptions(
            name='individual_segment',
            options={'ordering': ['ind_seg_id']},
        ),
        migrations.AlterModelOptions(
            name='segment_list',
            options={'ordering': ['seg_id']},
        ),
        migrations.AddField(
            model_name='actual',
            name='seg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfs.Segment_list'),
        ),
    ]
