# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0011_auto_20170926_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='actual_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
