# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0012_auto_20170926_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='excel_file',
            field=models.FileField(upload_to='projects/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
