# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0013_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment_list',
            name='seg_type',
            field=models.CharField(choices=[('IND', 'Individual'), ('GRP', 'Group')], max_length=10),
        ),
    ]
