# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0014_auto_20170926_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment_list',
            name='seg_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
