# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0015_auto_20170926_1645'),
        ('rfs', '0013_auto_20170926_1651'),
    ]

    operations = [
    ]
