# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfs.models


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0016_merge_20170926_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actual',
            options={'ordering': ['actual_id']},
        ),
        migrations.AlterModelOptions(
            name='segment_list',
            options={'ordering': ['seg_type']},
        ),
        migrations.RenameField(
            model_name='actual',
            old_name='ACTUAL_ARR',
            new_name='actual_arr',
        ),
        migrations.RenameField(
            model_name='actual',
            old_name='ACTUAL_REVENUE',
            new_name='actual_rev',
        ),
        migrations.RenameField(
            model_name='actual',
            old_name='ACTUAL_RNS',
            new_name='actual_rns',
        ),
        migrations.RenameField(
            model_name='actual',
            old_name='BUDGET_ARR',
            new_name='budget_arr',
        ),
        migrations.RenameField(
            model_name='actual',
            old_name='BUDGET_REVENUE',
            new_name='budget_rev',
        ),
        migrations.RenameField(
            model_name='actual',
            old_name='BUDGET_RNS',
            new_name='budget_rns',
        ),
        migrations.RenameField(
            model_name='actual',
            old_name='DATE',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='actual',
            name='PROJECT_ID',
        ),
        migrations.RemoveField(
            model_name='actual',
            name='SEG_ID',
        ),
        migrations.AddField(
            model_name='actual',
            name='seg_id',
            field=models.ForeignKey(blank=True, default='RCK', on_delete=django.db.models.deletion.CASCADE, to='rfs.Segment_list'),
        ),
        migrations.AlterField(
            model_name='actual',
            name='actual_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='excel_file',
            field=models.FileField(upload_to=rfs.models.project_directory_path),
        ),
    ]
