# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfs', '0016_merge_20170926_1724'),
        ('rfs', '0017_auto_20170926_1713'),
    ]

    operations = [
    ]
